# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fluxswitch < Formula
  desc "Switch between Flux CLI versions, tfswitch-style"
  homepage "https://github.com/haney-oliver/fluxswitch"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/haney-oliver/fluxswitch/releases/download/v0.1.0/fluxswitch_0.1.0_darwin_amd64.tar.gz"
      sha256 "4d00642f368b072e37be818e9dd846c7dab50e23202b1212337826f280f3fe38"

      define_method(:install) do
        bin.install "fluxswitch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/haney-oliver/fluxswitch/releases/download/v0.1.0/fluxswitch_0.1.0_darwin_arm64.tar.gz"
      sha256 "ad381dedd061d91c93aaf1f7ac5ba4c5bb7d4d6bf16ff01e6980253b21611bfc"

      define_method(:install) do
        bin.install "fluxswitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/haney-oliver/fluxswitch/releases/download/v0.1.0/fluxswitch_0.1.0_linux_amd64.tar.gz"
      sha256 "ff7cb6196059028b4419d73d0e5806301090344aafe26e04a95e67f201f80805"
      define_method(:install) do
        bin.install "fluxswitch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haney-oliver/fluxswitch/releases/download/v0.1.0/fluxswitch_0.1.0_linux_arm64.tar.gz"
      sha256 "897efefcd9ff224beb02cdc2d141f42b19711476a4ef350f60ec60a912e51430"
      define_method(:install) do
        bin.install "fluxswitch"
      end
    end
  end

  def caveats
    <<~EOS
      fluxswitch keeps flux binaries in ~/.fluxswitch and points a symlink
      at the active version. Add it to your PATH:
        export PATH="$HOME/.fluxswitch/bin:$PATH"
    EOS
  end

  test do
    system "#{bin}/fluxswitch", "--help"
  end
end
