# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fluxswitch < Formula
  desc "Switch between Flux CLI versions, tfswitch-style"
  homepage "https://github.com/everythingisacomputer/fluxswitch"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/everythingisacomputer/fluxswitch/releases/download/v0.1.1/fluxswitch_0.1.1_darwin_amd64.tar.gz"
      sha256 "314c2307b5f908292e50e8205108347f351229fc2c976ff4355a71fe32936105"

      define_method(:install) do
        bin.install "fluxswitch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/everythingisacomputer/fluxswitch/releases/download/v0.1.1/fluxswitch_0.1.1_darwin_arm64.tar.gz"
      sha256 "7c7da8349926f22279f1f81d2848f5af3e78cb15b64ea17743ad4627871c5a4d"

      define_method(:install) do
        bin.install "fluxswitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/everythingisacomputer/fluxswitch/releases/download/v0.1.1/fluxswitch_0.1.1_linux_amd64.tar.gz"
      sha256 "c507df310079b598e6847079e0f08bf90bfa44f27457c7cf95d84e12ac8d30c3"
      define_method(:install) do
        bin.install "fluxswitch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/everythingisacomputer/fluxswitch/releases/download/v0.1.1/fluxswitch_0.1.1_linux_arm64.tar.gz"
      sha256 "d6c81b13d7aad48f4f5cf286d4f134929a04fc4f3c7ebdeefca2bf0f9c358d57"
      define_method(:install) do
        bin.install "fluxswitch"
      end
    end
  end

  def caveats
    <<~EOS
      fluxswitch keeps flux binaries in ~/.fluxswitch and points a symlink
      at the active version. Add it to your PATH:
        export PATH="$HOME/.fluxswitch/bin:$PATH"
    EOS
  end

  test do
    system "#{bin}/fluxswitch", "--help"
  end
end
