# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fluxboost < Formula
  desc "Scaffold Flux GitOps repos, platform services, and tenants"
  homepage "https://github.com/everythingisacomputer/fluxboost"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/everythingisacomputer/fluxboost/releases/download/v0.1.0/fluxboost_0.1.0_darwin_amd64.tar.gz"
      sha256 "b8f1834764ed54efc44413c48c636a602019fae392e493f058e13d87ec4db8d8"

      define_method(:install) do
        bin.install "fluxboost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/everythingisacomputer/fluxboost/releases/download/v0.1.0/fluxboost_0.1.0_darwin_arm64.tar.gz"
      sha256 "9e708eb61895f9c367585cdec3448b494aa7e2e4c665c353eca8275b2e449424"

      define_method(:install) do
        bin.install "fluxboost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/everythingisacomputer/fluxboost/releases/download/v0.1.0/fluxboost_0.1.0_linux_amd64.tar.gz"
      sha256 "8ce7fd085035bf5030648669e5ada3def9daad38199cc34ab88a27e57d3a4eb2"
      define_method(:install) do
        bin.install "fluxboost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/everythingisacomputer/fluxboost/releases/download/v0.1.0/fluxboost_0.1.0_linux_arm64.tar.gz"
      sha256 "bf90bb0f9c40586721d01b71b9a8a0b5b9c7198d3b44550a7adafec63da48854"
      define_method(:install) do
        bin.install "fluxboost"
      end
    end
  end

  def caveats
    <<~EOS
      Run `fluxboost init` in an empty directory to scaffold a GitOps repo.
      fluxboost renders manifests for flux 2.7 - 2.9 and detects the flux
      CLI on your PATH.
    EOS
  end

  test do
    system "#{bin}/fluxboost", "version"
  end
end
